---
title: "Références bibliographiques"
lightbox: true
toc: true
---

::: {#ZAN style="font-family: YACkoD1yZN0-0;letter-spacing: 0.089em;font-size:1.0em;"}
## ZAN (Zéro Artificialisation Nette)

L'objectif ZAN consiste à limiter toute extension de l'artificialisation d'ici 2050. Cela implique que des aménagements des espaces agricoles, naturels ou forestiers seront encore possibles mais conditionnés à une renaturation à proportion égale d’espaces artificialisés sur le territoire concerné. Tout ce qui sera consommé devra être compensé pour équilibrer la balance au terme du délai imposé en 2050.
La  loi visant à renforcer l'accompagnement des élus locaux dans la mise en oeuvre des ZAN  dite "loi ZAN" du 20 juillet 2023 renforce ce principe tout en apportant quelques souplesses:
- une garantie communale de 1ha est accordée aux communes disposant d'un document d'urbanisme, sous réserve de justifier du besoin,
- une identification des projets d'envergure nationale pour les comptabiliser hors de l'enveloppe territoriale,
- un report du délai d'évolution pour la prise en compte du ZAN par les documents d'urbanisme. "
:::
